### ISSUE TITLE
Create customer payment example is not working

### ISSUE THREAD

**Issue by miguelsosa** [AuthorizeNet/sample-code-ruby#39]
When I try the CustomerProfiles/create-customer-profile.rb example I get:

> Failed to create a new customer payment profile: The record cannot be found.
> 
> The element 'paymentProfiles' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' cannot contain text. List of possible elements expected: 'customerType, billTo, payment, driversLicense, taxId, defaultPaymentProfile' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.
> CustomerProfiles/create-customer-profile.rb:36:in `create_customer_profile': Failed to create a new customer profile. (RuntimeError)

**Comment by miguelsosa** [comment]
rspecs are failing because of this:

  ```
1) SampleCode Testing should be able to run all Customer Profile sample code
     Failure/Error: response = create_customer_profile()

     RuntimeError:
       Failed to create a new customer profile.
     # ./CustomerProfiles/create-customer-profile.rb:36:in `create_customer_profile'
     # ./spec/sample_code_spec.rb:55:in `block (2 levels) in <top (required)>'
```

**Comment by miguelsosa** [comment]
This si fixed by sdk-ruby pull request 94 (https://github.com/AuthorizeNet/sdk-ruby/pull/94).
